#!/usr/bin/env node

// Please don't edit this file directly. It is compiled from the CoffeeScript
// in summon.coffee. If you edit the CoffeeScript source and compile its changes,
// please keep the commits to this file separate. See the README for instructions
// on setting up a pre-commit hook to help with that.

var async, exec, getPlatformInstallers, nopt, options, packageName, readline, runInstallCommand, spawn, testCommand, tryToInstall, userInput;

exec = require('child_process').exec;

spawn = require('child_process').spawn;

readline = require('readline');

async = require('async');

nopt = require('nopt');

options = nopt({
  testCommand: [String],
  manager: [Array, String]
});

userInput = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

if (!(options.argv.remain.length > 0)) {
  console.log('Pass the package name you want to install as the first argument.');
  console.log('Usage: ./summon [packageName]');
  console.log('Example: ./summon git');
  process.exit(1);
}

packageName = options.argv.remain[0];

testCommand = options.testCommand ? options.testCommand : packageName;

exec("command -v " + testCommand).on('exit', function(code) {
  if (code === 0) {
    process.exit(0);
  }
  console.log("You are missing " + packageName + ", which is a required dependency.");
  return tryToInstall();
});

tryToInstall = function() {
  return userInput.question("Do you want to try to install " + packageName + " automatically? (Y/n) ", function(answer) {
    var installers;

    if (/^n/i.test(answer)) {
      console.log("\nPlease install " + packageName + " and then re-run this installer.");
      process.exit(1);
    }
    console.log("Okay, let's try to install " + packageName + ".\n");
    installers = getPlatformInstallers();
    return async.filter(installers, function(installer, callback) {
      return exec("command -v " + installer).on('exit', function(code) {
        return callback(code === 0);
      });
    }, function(installers) {
      var index, installer, _i, _len;

      if (installers.length === 0) {
        console.log("We couldn't find any package managers.");
        console.log("Please install " + packageName + " and then re-run this installer.");
        process.exit(1);
      }
      console.log("We looked for package managers and found:");
      for (index = _i = 0, _len = installers.length; _i < _len; index = ++_i) {
        installer = installers[index];
        console.log("" + (index + 1) + ") " + installer);
      }
      return userInput.question("\nDo you want to use one of these? Or let us know what command you prefer. (1/#/[command]) ", function(choice) {
        if (/^\d+$/.test(choice)) {
          installer = installers[choice - 1];
        } else if (choice) {
          installer = choice;
        } else {
          installer = installers[0];
          console.log("Using the default installer: " + installer);
        }
        if (!installer) {
          console.log('\nOops, not a valid choice.');
          process.exit(1);
        }
        return runInstallCommand(installer, packageName);
      });
    });
  });
};

runInstallCommand = function(installer, command) {
  var _package;

  _package = options[installer] ? options[installer] : packageName;
  command = "" + installer + " install " + _package;
  console.log("\nOkay, going to try running: " + command + "\n");
  return userInput.question('Good to go? (Y/n) ', function(answer) {
    if (answer && /^n/i.test(answer)) {
      console.log("\nOkay, we won't do it. You're on your own for installing " + packageName + ".");
      process.exit(0);
    }
    return userInput.question('Does this command need sudo? (y/N) ', function(maybe_sudo) {
      var install;

      if (/^y(es)?$/i.test(maybe_sudo)) {
        command = "sudo " + command;
      }
      install = spawn(command.split(' ')[0], command.split(' ').slice(1));
      install.stdout.pipe(process.stdout, {
        end: false
      });
      process.stdin.resume();
      process.stdin.pipe(install.stdin, {
        end: false
      });
      return install.on('close', function(code) {
        if (code === 0) {
          console.log('\nAwesome, that worked! Enjoy!');
          return process.exit(0);
        } else {
          console.log("\nUh oh, looks like that didn't work.");
          console.log("Please install " + packageName + " and then re-run this installer.");
          return process.exit(code);
        }
      });
    });
  });
};

getPlatformInstallers = function() {
  if (process.platform === "linux" && process.arch === "x64") {
    return ["apt-get", "yum"];
  } else if (process.platform === "darwin") {
    return ["brew", "port", "fink"];
  } else if (process.platform === "win32") {
    return ["apt-cyg"];
  } else {
    return [];
  }
};
