#!/usr/bin/env bash

if [[ -n "$npm_package_name" && "$npm_package_name" != "summon" ]]; then
  exit 0;
fi

PROJECT_DIR=$(git rev-parse --show-toplevel)
cd $PROJECT_DIR

# Link scripts
if [ -f "$PROJECT_DIR/.git/hooks/pre-commit" ]; then
	echo
	echo
	read -p "You have a Git pre-commit script, can we overwrite it? (y/N)" yn
	case $yn in
		[Yy]* ) echo "Okay, overwriting it.";;
		[Nn]* ) exit 0;;
	esac
fi

ln -nfs $PROJECT_DIR/scripts/git/pre-commit $PROJECT_DIR/.git/hooks/pre-commit
